# SPDX-License-Identifier: Apache-2.0
"""US2 integration test — byte-level tamper detection (SC-004).

Quickstart scenario 2 from spec.md §US2:
  1. Write 5 valid consent ledger records via ``ledger.append()``.
  2. Flip 1 byte at offset 100 in the raw ledger file.
  3. Run the verifier — must exit code 1 with ``CHAIN_RECORD_HASH_MISMATCH``
     and ``first_broken_index=0``.

Also tests:
  - Byte flip in later records (first_broken_index == N).
  - Byte flip at various offsets (beginning, middle, end of record).
  - Tamper via hmac_seal flip → exit 2.

Reference: specs/033-permission-v2-spectrum/spec.md §US2 SC-004
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import pytest

from kosmos.permissions.ledger import append as ledger_append
from kosmos.permissions.ledger_verify import verify_ledger

# ---------------------------------------------------------------------------
# Fixture: temporary ledger environment
# ---------------------------------------------------------------------------


@pytest.fixture()
def ledger_env(tmp_path: Path):
    """Create a complete ledger environment (keys + ledger) and return paths."""
    keys_dir = tmp_path / "keys"
    keys_dir.mkdir(mode=0o700, parents=True)
    key_path = keys_dir / "ledger.key"
    key_registry_path = keys_dir / "registry.json"
    ledger_path = tmp_path / "consent_ledger.jsonl"

    # Key will be auto-generated by ledger.append() via load_or_generate_key.
    # Write registry pointing to ledger.key with key_id k0001.
    import json

    key_registry_path.write_text(
        json.dumps([{"key_id": "k0001", "retired_at": None, "file_path": "ledger.key"}]),
        encoding="utf-8",
    )

    return {
        "key_path": key_path,
        "key_registry_path": key_registry_path,
        "ledger_path": ledger_path,
        "tmp_path": tmp_path,
    }


def _write_5_records(env: dict) -> None:
    """Append 5 valid consent decisions to the ledger."""
    for i in range(5):
        seed = f"action_{i}_nonce_{os.urandom(8).hex()}".encode()
        action_digest = hashlib.sha256(seed).hexdigest()
        ledger_append(
            tool_id="test_tool",
            mode="default",
            granted=True,
            action_digest=action_digest,
            ledger_path=env["ledger_path"],
            key_path=env["key_path"],
            key_registry_path=env["key_registry_path"],
        )


# ---------------------------------------------------------------------------
# SC-004: Flip byte at offset 100 → exit 1, first_broken_index=0
# ---------------------------------------------------------------------------


def test_us2_flip_byte_offset_100(ledger_env: dict) -> None:
    """US2 quickstart: flip 1 byte at offset 100 → exit 1, first_broken_index=0."""
    _write_5_records(ledger_env)
    ledger_path: Path = ledger_env["ledger_path"]
    key_registry_path: Path = ledger_env["key_registry_path"]

    # Read file and flip byte at offset 100.
    raw = bytearray(ledger_path.read_bytes())
    assert len(raw) > 100, f"Ledger too short: {len(raw)} bytes"
    raw[100] ^= 0xFF  # XOR-flip the byte
    ledger_path.write_bytes(bytes(raw))

    report = verify_ledger(
        ledger_path=ledger_path,
        key_registry_path=key_registry_path,
    )

    assert report.exit_code == 1, f"Expected exit 1, got {report.exit_code}: {report.broken_reason}"
    assert report.passed is False
    assert report.broken_reason in ("CHAIN_RECORD_HASH_MISMATCH", "CHAIN_PREV_HASH_MISMATCH")
    assert report.first_broken_index == 0


# ---------------------------------------------------------------------------
# SC-004: Flip byte in record N (middle of file) → exit 1
# ---------------------------------------------------------------------------


def test_us2_flip_byte_in_middle_record(ledger_env: dict) -> None:
    """Flip 1 byte in the 3rd record → exit 1, chain broken at record >= 2."""
    _write_5_records(ledger_env)
    ledger_path: Path = ledger_env["ledger_path"]
    key_registry_path: Path = ledger_env["key_registry_path"]

    # Find the start of the 3rd line (index 2).
    lines = ledger_path.read_bytes().split(b"\n")
    # Compute byte offset of line 2 (0-indexed).
    offset = sum(len(lines[i]) + 1 for i in range(2))  # +1 for \n
    assert offset < len(b"\n".join(lines)), "Offset beyond file"

    raw = bytearray(ledger_path.read_bytes())
    # Flip a byte in the middle of line 2.
    flip_offset = offset + 5
    if flip_offset < len(raw):
        raw[flip_offset] ^= 0x01
    ledger_path.write_bytes(bytes(raw))

    report = verify_ledger(
        ledger_path=ledger_path,
        key_registry_path=key_registry_path,
    )

    assert report.exit_code == 1
    assert report.passed is False
    assert report.first_broken_index is not None


# ---------------------------------------------------------------------------
# SC-004: Flip byte in hmac_seal → exit 2 (HMAC_SEAL_MISMATCH)
# ---------------------------------------------------------------------------


def test_us2_flip_hmac_seal_only(ledger_env: dict) -> None:
    """Tamper hmac_seal of record 0 only (keep all other fields intact) → exit 2."""
    import json

    _write_5_records(ledger_env)
    ledger_path: Path = ledger_env["ledger_path"]
    key_registry_path: Path = ledger_env["key_registry_path"]

    lines = ledger_path.read_text("utf-8").splitlines()
    rec0 = json.loads(lines[0])
    original_seal = rec0["hmac_seal"]
    # Flip the first character to a different hex digit.
    first_char = original_seal[0]
    flipped_char = "1" if first_char != "1" else "2"
    rec0["hmac_seal"] = flipped_char + original_seal[1:]
    lines[0] = json.dumps(rec0, ensure_ascii=False, separators=(",", ":"))
    ledger_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    report = verify_ledger(
        ledger_path=ledger_path,
        key_registry_path=key_registry_path,
    )

    assert report.exit_code == 2
    assert report.passed is False
    assert report.broken_reason == "HMAC_SEAL_MISMATCH"
    assert report.first_broken_index == 0


# ---------------------------------------------------------------------------
# Positive: 5 records appended and verified without tampering → exit 0
# ---------------------------------------------------------------------------


def test_us2_5_records_clean_verify(ledger_env: dict) -> None:
    """5 valid records written by ledger.append() verify cleanly → exit 0."""
    _write_5_records(ledger_env)
    ledger_path: Path = ledger_env["ledger_path"]
    key_registry_path: Path = ledger_env["key_registry_path"]

    report = verify_ledger(
        ledger_path=ledger_path,
        key_registry_path=key_registry_path,
    )

    assert report.exit_code == 0
    assert report.passed is True
    assert report.total_records == 5
    assert report.first_broken_index is None
    assert report.broken_reason is None


# ---------------------------------------------------------------------------
# Invariant L1: genesis record has prev_hash == "0" * 64
# ---------------------------------------------------------------------------


def test_us2_genesis_prev_hash(ledger_env: dict) -> None:
    """First record appended must have prev_hash == '0' * 64 (Invariant L1)."""
    import json

    ledger_append(
        tool_id="test_tool",
        mode="default",
        granted=True,
        action_digest=hashlib.sha256(b"test").hexdigest(),
        ledger_path=ledger_env["ledger_path"],
        key_path=ledger_env["key_path"],
        key_registry_path=ledger_env["key_registry_path"],
    )

    lines = ledger_env["ledger_path"].read_text("utf-8").splitlines()
    rec = json.loads(lines[0])
    assert rec["prev_hash"] == "0" * 64, "Genesis prev_hash must be 64 zeros"


# ---------------------------------------------------------------------------
# Invariant L5 (WORM): append produces correct sequence numbers
# ---------------------------------------------------------------------------


def test_us2_sequence_increments(ledger_env: dict) -> None:
    """Sequence numbers must be monotonically increasing (Invariant L5 / L2)."""
    import json

    _write_5_records(ledger_env)
    lines = ledger_env["ledger_path"].read_text("utf-8").splitlines()
    sequences = [json.loads(line)["sequence"] for line in lines if line.strip()]
    assert sequences == list(range(5)), f"Unexpected sequences: {sequences}"


# ---------------------------------------------------------------------------
# Chain linkage: record[N].prev_hash == record[N-1].record_hash
# ---------------------------------------------------------------------------


def test_us2_chain_linkage(ledger_env: dict) -> None:
    """Every record's prev_hash must equal the previous record's record_hash."""
    import json

    _write_5_records(ledger_env)
    raw_lines = ledger_env["ledger_path"].read_text("utf-8").splitlines()
    lines = [json.loads(line) for line in raw_lines if line.strip()]

    assert lines[0]["prev_hash"] == "0" * 64
    for i in range(1, len(lines)):
        assert lines[i]["prev_hash"] == lines[i - 1]["record_hash"], (
            f"Chain broken at record {i}: "
            f"prev_hash={lines[i]['prev_hash']!r} "
            f"!= record_hash[{i - 1}]={lines[i - 1]['record_hash']!r}"
        )


# ---------------------------------------------------------------------------
# SC-004: Multiple single-byte flips at different positions all detected
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("offset", [0, 10, 50, 100, 150, 200])
def test_us2_single_byte_flip_detected(ledger_env: dict, offset: int, tmp_path: Path) -> None:
    """SC-004: Single-byte flip at various offsets must be detected (exit != 0)."""
    # Write fresh records for each parametrized run.

    env = {
        "key_path": ledger_env["key_path"],
        "key_registry_path": ledger_env["key_registry_path"],
        "ledger_path": tmp_path / f"ledger_{offset}.jsonl",
        "tmp_path": tmp_path,
    }

    _write_5_records(env)
    ledger_path: Path = env["ledger_path"]
    raw = bytearray(ledger_path.read_bytes())

    if offset >= len(raw):
        pytest.skip(f"Offset {offset} beyond file size {len(raw)}")

    raw[offset] ^= 0xFF
    ledger_path.write_bytes(bytes(raw))

    report = verify_ledger(
        ledger_path=ledger_path,
        key_registry_path=env["key_registry_path"],
    )

    assert report.exit_code != 0, (
        f"Single-byte flip at offset {offset} was NOT detected! "
        f"exit_code={report.exit_code}, reason={report.broken_reason}"
    )
