// ============================================================
// DO NOT EDIT — generated by tui/scripts/gen-ipc-types.ts
// Source of truth: src/kosmos/ipc/frame_schema.py (Pydantic v2)
// FR-003: TypeScript types are derived from Pydantic models.
// Regenerate: bun run gen:ipc
// Drift check: bun run gen:ipc -- --check
// ============================================================

/* eslint-disable */
// @ts-nocheck

export type IPCFrame =
  | UserInputFrame
  | AssistantChunkFrame
  | ToolCallFrame
  | ToolResultFrame
  | CoordinatorPhaseFrame
  | WorkerStatusFrame
  | PermissionRequestFrame
  | PermissionResponseFrame
  | SessionEventFrame
  | ErrorFrame;
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts = string;
/**
 * Frame discriminator.
 */
export type Kind = 'user_input';
/**
 * Raw user text in UTF-8 (may contain Korean, English, emoji).
 */
export type Text = string;
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId1 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId1 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts1 = string;
/**
 * Frame discriminator.
 */
export type Kind1 = 'assistant_chunk';
/**
 * ULID of the assistant message this delta belongs to.
 */
export type MessageId = string;
/**
 * UTF-8 text appended to the message.
 */
export type Delta = string;
/**
 * True if this is the terminal chunk for this message_id.
 */
export type Done = boolean;
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId2 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId2 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts2 = string;
/**
 * Frame discriminator.
 */
export type Kind2 = 'tool_call';
/**
 * ULID correlating this call to its subsequent tool_result.
 */
export type CallId = string;
/**
 * Primitive name per Spec 031.
 */
export type Name = 'lookup' | 'resolve_location' | 'submit' | 'subscribe' | 'verify';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId3 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId3 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts3 = string;
/**
 * Frame discriminator.
 */
export type Kind3 = 'tool_result';
/**
 * ULID correlating this result to its originating tool_call.
 */
export type CallId1 = string;
/**
 * Primitive kind discriminator per Spec 031.
 */
export type Kind4 = 'lookup' | 'resolve_location' | 'submit' | 'subscribe' | 'verify';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId4 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId4 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts4 = string;
/**
 * Frame discriminator.
 */
export type Kind5 = 'coordinator_phase';
/**
 * Current coordinator phase.
 */
export type Phase = 'Research' | 'Synthesis' | 'Implementation' | 'Verification';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId5 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId5 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts5 = string;
/**
 * Frame discriminator.
 */
export type Kind6 = 'worker_status';
/**
 * Unique worker identifier.
 */
export type WorkerId = string;
/**
 * Specialist label (e.g., transport-specialist, health-specialist).
 */
export type RoleId = string;
/**
 * Primitive currently being invoked by this worker.
 */
export type CurrentPrimitive = 'lookup' | 'resolve_location' | 'submit' | 'subscribe' | 'verify';
/**
 * Worker execution status.
 */
export type Status = 'idle' | 'running' | 'waiting_permission' | 'error';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId6 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId6 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts6 = string;
/**
 * Frame discriminator.
 */
export type Kind7 = 'permission_request';
/**
 * ULID; round-trips in the matching permission_response frame.
 */
export type RequestId = string;
/**
 * Worker requesting permission.
 */
export type WorkerId1 = string;
/**
 * The primitive the worker wants to invoke.
 */
export type PrimitiveKind = 'lookup' | 'resolve_location' | 'submit' | 'subscribe' | 'verify';
/**
 * Korean-language description shown to the citizen.
 */
export type DescriptionKo = string;
/**
 * English-language description shown alongside the Korean one.
 */
export type DescriptionEn = string;
/**
 * Risk classification of the requested operation.
 */
export type RiskLevel = 'low' | 'medium' | 'high';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId7 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId7 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts7 = string;
/**
 * Frame discriminator.
 */
export type Kind8 = 'permission_response';
/**
 * ULID matching the originating permission_request.request_id.
 */
export type RequestId1 = string;
/**
 * Citizen's permission decision.
 */
export type Decision = 'granted' | 'denied';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId8 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId8 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts8 = string;
/**
 * Frame discriminator.
 */
export type Kind9 = 'session_event';
/**
 * Session lifecycle event type.
 */
export type Event = 'save' | 'load' | 'list' | 'resume' | 'new' | 'exit';
/**
 * ULID; shared across all frames in a session.
 */
export type SessionId9 = string;
/**
 * ULID of the triggering frame; null for unsolicited frames.
 */
export type CorrelationId9 = string | null;
/**
 * RFC 3339 UTC timestamp.
 */
export type Ts9 = string;
/**
 * Frame discriminator.
 */
export type Kind10 = 'error';
/**
 * Machine-readable error code (e.g., 'backend_crash', 'protocol_mismatch').
 */
export type Code = string;
/**
 * Human-readable short message. MUST NOT contain KOSMOS_*-prefixed env var values (FR-004 redaction rule).
 */
export type Message = string;

/**
 * TUI → backend: a citizen's typed input.
 */
export interface UserInputFrame {
  session_id: SessionId;
  correlation_id?: CorrelationId;
  ts: Ts;
  kind: Kind;
  text: Text;
}
/**
 * backend → TUI: streaming assistant text delta.
 */
export interface AssistantChunkFrame {
  session_id: SessionId1;
  correlation_id?: CorrelationId1;
  ts: Ts1;
  kind: Kind1;
  message_id: MessageId;
  delta: Delta;
  done: Done;
}
/**
 * backend → TUI (display only): a tool invocation decision by the model.
 */
export interface ToolCallFrame {
  session_id: SessionId2;
  correlation_id?: CorrelationId2;
  ts: Ts2;
  kind: Kind2;
  call_id: CallId;
  name: Name;
  arguments: Arguments;
}
/**
 * Primitive-specific arguments; shape per Spec 031 input schemas.
 */
export interface Arguments {
  [k: string]: any;
}
/**
 * backend → TUI (render): the output of a tool invocation.
 */
export interface ToolResultFrame {
  session_id: SessionId3;
  correlation_id?: CorrelationId3;
  ts: Ts3;
  kind: Kind3;
  call_id: CallId1;
  envelope: ToolResultEnvelope;
}
/**
 * 5-primitive discriminated union. Unknown kind falls to UnrecognizedPayload.
 */
export interface ToolResultEnvelope {
  kind: Kind4;
  [k: string]: any;
}
/**
 * backend → TUI: Spec 027 coordinator phase update.
 */
export interface CoordinatorPhaseFrame {
  session_id: SessionId4;
  correlation_id?: CorrelationId4;
  ts: Ts4;
  kind: Kind5;
  phase: Phase;
}
/**
 * backend → TUI: per-worker status row update from Spec 027 swarm.
 */
export interface WorkerStatusFrame {
  session_id: SessionId5;
  correlation_id?: CorrelationId5;
  ts: Ts5;
  kind: Kind6;
  worker_id: WorkerId;
  role_id: RoleId;
  current_primitive: CurrentPrimitive;
  status: Status;
}
/**
 * backend → TUI: a worker raises a permission request.
 */
export interface PermissionRequestFrame {
  session_id: SessionId6;
  correlation_id?: CorrelationId6;
  ts: Ts6;
  kind: Kind7;
  request_id: RequestId;
  worker_id: WorkerId1;
  primitive_kind: PrimitiveKind;
  description_ko: DescriptionKo;
  description_en: DescriptionEn;
  risk_level: RiskLevel;
}
/**
 * TUI → backend: citizen's decision on a permission_request.
 */
export interface PermissionResponseFrame {
  session_id: SessionId7;
  correlation_id?: CorrelationId7;
  ts: Ts7;
  kind: Kind8;
  request_id: RequestId1;
  decision: Decision;
}
/**
 * Bidirectional: session lifecycle events.
 */
export interface SessionEventFrame {
  session_id: SessionId8;
  correlation_id?: CorrelationId8;
  ts: Ts8;
  kind: Kind9;
  event: Event;
  payload: Payload;
}
/**
 * Event-specific payload. For list: {sessions: [{id, created_at, turn_count}]}. For resume: {id: str}. For others: {}.
 */
export interface Payload {
  [k: string]: any;
}
/**
 * backend → TUI: a backend error surfaced to the TUI for rendering.
 */
export interface ErrorFrame {
  session_id: SessionId9;
  correlation_id?: CorrelationId9;
  ts: Ts9;
  kind: Kind10;
  code: Code;
  message: Message;
  details: Details;
}
/**
 * Structured error details. KOSMOS_* env var values MUST be redacted.
 */
export interface Details {
  [k: string]: any;
}
