// ============================================================
// DO NOT EDIT — generated by tui/scripts/gen-pipa-hash.ts
// Source of truth: src/kosmos/plugins/canonical_acknowledgment.py
//   (which extracts the canonical text from
//   docs/plugins/security-review.md between the
//   <!-- CANONICAL-PIPA-ACK-* --> markers).
// Regenerate: bun run scripts/gen-pipa-hash.ts
// Drift check: bun run scripts/gen-pipa-hash.ts --check
// ============================================================

/* eslint-disable */
// @ts-nocheck

export const CANONICAL_PIPA_ACK_SHA256 = "434074581cab35241c70f9b6e2191a7220fdac67aa627289ea64472cb87495d4" as const
