#!/usr/bin/env bun
/**
 * gen-pipa-hash.ts — Sync the PIPA §26 canonical hash from the Python
 * source-of-truth (`docs/plugins/security-review.md` extracted via
 * `kosmos.plugins.canonical_acknowledgment.CANONICAL_ACKNOWLEDGMENT_SHA256`)
 * into a generated TypeScript file consumed by the `/plugin pipa-text`
 * slash command.
 *
 * This closes review eval C4 — previously `tui/src/commands/plugin.ts`
 * hard-coded the hash, which would silently drift the moment legal team
 * approves a new canonical text.
 *
 * Usage:
 *   bun run scripts/gen-pipa-hash.ts          # write
 *   bun run scripts/gen-pipa-hash.ts --check  # CI drift gate
 */

import { writeFileSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const SCRIPT_DIR = import.meta.dir
const TUI_ROOT = join(SCRIPT_DIR, '..')
const KOSMOS_ROOT = join(TUI_ROOT, '..')
const OUT_FILE = join(TUI_ROOT, 'src', 'ipc', 'pipa.generated.ts')

const PY_SNIPPET = [
  'from kosmos.plugins.canonical_acknowledgment import CANONICAL_ACKNOWLEDGMENT_SHA256',
  'import sys',
  'sys.stdout.write(CANONICAL_ACKNOWLEDGMENT_SHA256)',
].join('; ')

async function fetchHash(): Promise<string> {
  const proc = Bun.spawn(['uv', 'run', 'python', '-c', PY_SNIPPET], {
    cwd: KOSMOS_ROOT,
    stdout: 'pipe',
    stderr: 'pipe',
  })
  const exitCode = await proc.exited
  const stdout = await new Response(proc.stdout).text()
  const stderr = await new Response(proc.stderr).text()
  if (exitCode !== 0) {
    throw new Error(`uv run failed (${exitCode}): ${stderr}`)
  }
  const hash = stdout.trim()
  if (!/^[a-f0-9]{64}$/.test(hash)) {
    throw new Error(`hash shape invalid: ${JSON.stringify(hash)}`)
  }
  return hash
}

const BANNER = `// ============================================================
// DO NOT EDIT — generated by tui/scripts/gen-pipa-hash.ts
// Source of truth: src/kosmos/plugins/canonical_acknowledgment.py
//   (which extracts the canonical text from
//   docs/plugins/security-review.md between the
//   <!-- CANONICAL-PIPA-ACK-* --> markers).
// Regenerate: bun run scripts/gen-pipa-hash.ts
// Drift check: bun run scripts/gen-pipa-hash.ts --check
// ============================================================
`

function render(hash: string): string {
  return (
    BANNER +
    '\n' +
    '/* eslint-disable */\n' +
    '// @ts-nocheck\n' +
    '\n' +
    'export const CANONICAL_PIPA_ACK_SHA256 = ' +
    JSON.stringify(hash) +
    ' as const\n'
  )
}

const args = process.argv.slice(2)
const isCheck = args.includes('--check')

const hash = await fetchHash()
const expected = render(hash)

if (isCheck) {
  let onDisk = ''
  try {
    onDisk = readFileSync(OUT_FILE, 'utf-8')
  } catch {
    console.error(`gen-pipa-hash --check: ${OUT_FILE} missing — run gen-pipa-hash.ts to create it.`)
    process.exit(1)
  }
  if (onDisk !== expected) {
    console.error(
      `gen-pipa-hash --check: drift detected. Run \`bun run scripts/gen-pipa-hash.ts\` and commit.`,
    )
    process.exit(1)
  }
  console.log(`gen-pipa-hash --check: OK (${hash})`)
  process.exit(0)
}

writeFileSync(OUT_FILE, expected, 'utf-8')
console.log(`gen-pipa-hash: wrote ${OUT_FILE} (${hash})`)
